# Generated by Django 6.0.4 on 2026-04-29 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='name', default='', max_length=100)),
                ('mission_statement', models.TextField(blank=True, default='')),
                ('workstream_mf', models.TextField(blank=True, default='')),
                ('focus_areas', models.TextField(blank=True, default='')),
                ('skills_technologies', models.TextField(blank=True, default='')),
                ('slack_channels', models.TextField(blank=True, default='')),
                ('standup_details', models.TextField(blank=True, default='')),
                ('agile_practices', models.TextField(blank=True, default='')),
                ('team_wiki', models.TextField(blank=True, default='')),
                ('github_url', models.TextField(blank=True, default='')),
                ('jira_board_link', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.department')),
                ('lead_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, max_length=100)),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='teams.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
