# Generated by Django 6.0.4 on 2026-04-22 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='name', default='', max_length=100)),
                ('mission_statement', models.TextField(blank=True, default='')),
                ('workstream_mf', models.TextField(blank=True, default='')),
                ('focus_areas', models.TextField(blank=True, default='')),
                ('skills_technologies', models.TextField(blank=True, default='')),
                ('slack_channels', models.TextField(blank=True, default='')),
                ('standup_details', models.TextField(blank=True, default='')),
                ('agile_practices', models.TextField(blank=True, default='')),
                ('team_wiki', models.URLField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('dept', models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.department')),
                ('lead_user', models.ForeignKey(blank=True, db_column='lead_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
