# Generated by Django 6.0.4 on 2026-04-23 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('jira_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_board_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='software_owned',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='agile_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='team',
            name='focus_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='lead_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='skills_technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slack_channels',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='standup_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_wiki',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='workstream_mf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.project'),
        ),
    ]
