# Generated by Django 6.0.4 on 2026-04-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_project_team_github_url_team_jira_board_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='jira_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='software_owned',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='agile_practices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='focus_areas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='jira_board_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='mission_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='skills_technologies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='slack_channels',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='standup_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(db_column='name', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_wiki',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='workstream_mf',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, max_length=100)),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='teams.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='teams.team')),
            ],
        ),
    ]
