# Generated by Django 6.0.4 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_description_team_team_lead_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
