# Generated by Django 6.0.3 on 2026-04-10 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("teams", "0003_team_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="team",
                    name="department",
                ),
                migrations.RemoveField(
                    model_name="team",
                    name="description",
                ),
                migrations.RemoveField(
                    model_name="team",
                    name="id",
                ),
                migrations.RemoveField(
                    model_name="team",
                    name="location",
                ),
                migrations.RemoveField(
                    model_name="team",
                    name="name",
                ),
                migrations.RemoveField(
                    model_name="team",
                    name="team_lead",
                ),
                migrations.AddField(
                    model_name="team",
                    name="team_id",
                    field=models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                migrations.AddField(
                    model_name="team",
                    name="team_name",
                    field=models.CharField(db_column="name", default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="team",
                    name="agile_practices",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="dept",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="dept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="organizations.department",
                    ),
                ),
                migrations.AddField(
                    model_name="team",
                    name="focus_areas",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="lead_user",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="lead_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="team",
                    name="mission_statement",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="skills_technologies",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="slack_channels",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="standup_details",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="status",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AddField(
                    model_name="team",
                    name="team_wiki",
                    field=models.URLField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="workstream_mf",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name="team",
                    name="agile_practices",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="dept",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="dept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="organizations.department",
                    ),
                ),
                migrations.AddField(
                    model_name="team",
                    name="focus_areas",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="lead_user",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="lead_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="team",
                    name="mission_statement",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="skills_technologies",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="slack_channels",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="standup_details",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="status",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AddField(
                    model_name="team",
                    name="team_wiki",
                    field=models.URLField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="team",
                    name="workstream_mf",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
    ]
