# Generated by Copilot on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_wiki',
            field=models.TextField(blank=True, default=''),
        ),
    ]
