# Generated by Copilot on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_team_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='jira_board_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
