# Generated by Django 6.0.4 on 2026-04-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_department_head_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_user',
            field=models.CharField(max_length=100, verbose_name='Head of Department'),
        ),
    ]
