# Generated by Django 6.0.4 on 2026-04-28 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-GB', 'English (United Kingdom)'), ('en-US', 'English (United States)')], default='en-GB', max_length=20)),
                ('display_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10)),
                ('time_format', models.CharField(choices=[('12_GMT', '12 hour, GMT'), ('24_GMT', '24 hour, GMT')], default='12_GMT', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
