# Generated by Django 6.0.4 on 2026-04-29 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('platform', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('upcoming', 'Upcoming'), ('reminder', 'Reminder'), ('task', 'Task'), ('meeting', 'Meeting')], default='meeting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, to='teams.team')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
