# Generated by Django 6.0.4 on 2026-04-16 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='platform',
            field=models.CharField(default='Online', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('upcoming', 'Upcoming')], default='weekly', max_length=20),
            preserve_default=False,
        ),
    ]
