# Generated by Django 6.0.4 on 2026-04-23 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_description_schedule_message_and_more'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.team'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='users',
            field=models.ManyToManyField(related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
