# Generated by Django 6.0.4 on 2026-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schedule_created_by_alter_schedule_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('upcoming', 'Upcoming'), ('reminder', 'Reminder'), ('task', 'Task'), ('meeting', 'Meeting')], default='meeting', max_length=20),
        ),
    ]
