# Generated by Django 6.0.4 on 2026-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_schedule_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('task', 'Task'), ('reminder', 'Reminder'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('upcoming', 'Upcoming')], default='meeting', max_length=20),
        ),
    ]
